### ISSUE TITLE
Broken on Python 3.4: SyntaxError: can use starred expression only as assignment target

### ISSUE THREAD

**Issue by drigz** [nadirizr/dazel#29]
If I run dazel==0.0.33 I get the following error:

```
> virtualenv -p python3 env
> env/bin/python3 --version
Python 3.4.3
> env/bin/pip install dazel==0.0.33
Collecting dazel==0.0.33
  Using cached dazel-0.0.33-py2.py3-none-any.whl
Installing collected packages: dazel
Successfully installed dazel-0.0.33
> env/bin/dazel version    
Traceback (most recent call last):
  File "env/bin/dazel", line 7, in <module>
    from dazel import main
  File "/usr/local/google/home/rodrigoq/git/google/glog/env/lib/python3.4/site-packages/dazel.py", line 138
    *shutil.get_terminal_size(),
               ^
SyntaxError: can use starred expression only as assignment target
```

This appears to be a Python 3.4 compatibility issue: https://github.com/karlch/vimiv/issues/7

**Comment by mishas** [comment]
This is going to be fixed by pull request #27, so stay tuned.
